[package]
name = "De-En_coder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
docx-rs = "0.4.18"
file-format = { version = "0.28.0", features = ["reader"] }
thiserror = "1.0.69"
